name: Deploy House Price Model

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.10'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install bentoml>=1.3.18

    - name: Login to BentoML Cloud
      env:
        BENTO_CLOUD_API_KEY: ${{ secrets.BENTO_CLOUD_API_KEY }}
        BENTO_CLOUD_API_ENDPOINT: ${{ secrets.BENTO_CLOUD_API_ENDPOINT }}
      run: |
        bentoml cloud login --api-token $BENTO_CLOUD_API_KEY --endpoint $BENTO_CLOUD_API_ENDPOINT
        bentoml cloud context set --name default --endpoint $BENTO_CLOUD_API_ENDPOINT

    - name: Build and Push Bento
      run: |
        bentoml build -f bentofile.yaml
        bentoml push

    - name: Get latest Bento tag
      id: get_tag
      run: |
        BENTO_TAG=$(bentoml list house_price_service -o json | jq -r '.[0].tag')
        echo "BENTO_TAG=${BENTO_TAG}" >> $GITHUB_ENV

    - name: Update Deployment
      env:
        BENTO_CLOUD_API_KEY: ${{ secrets.BENTO_CLOUD_API_KEY }}
        BENTO_CLOUD_API_ENDPOINT: ${{ secrets.BENTO_CLOUD_API_ENDPOINT }}
      run: |
        bentoml deployment update \
          --api-token $BENTO_CLOUD_API_KEY \
          --endpoint $BENTO_CLOUD_API_ENDPOINT \
          housing-model-v1 ${{ env.BENTO_TAG }}
