name: Deploy House Price Model

on:
  push:
    branches:
      - main

jobs:
  build_and_deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v5
        with:
          python-version: '3.10'
          cache: 'pip'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Build and Deploy
        uses: bentoml/deploy-bento-action@main
        with:
          deployment_name: housing-model-v1
          cloud_api_token: ${{ secrets.BENTO_CLOUD_API_KEY }}
          cloud_endpoint: ${{ secrets.BENTO_CLOUD_API_ENDPOINT }}
          action: 'update'
          bentoml_version: '1.3.18'
        id: deploy-bento

      - name: Display Bento Info
        run: |
          echo "Bento Repository: ${{ steps.deploy-bento.outputs.bento_repository }}"
          echo "Bento Version: ${{ steps.deploy-bento.outputs.bento_version }}"
          echo "Bento Tag: ${{ steps.deploy-bento.outputs.bento_tag }}" 