name: Deploy House Price Model

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.10'
        
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        
    - name: Configure BentoML Cloud
      env:
        BENTO_CLOUD_API_KEY: ${{ secrets.BENTO_CLOUD_API_KEY }}
        BENTO_CLOUD_API_ENDPOINT: ${{ secrets.BENTO_CLOUD_API_ENDPOINT }}
      run: |
        echo "Configuring BentoML Cloud..."
        # Create .bentoml/config.yaml
        mkdir -p ~/.bentoml
        cat > ~/.bentoml/config.yaml << EOF
        api_token: ${{ secrets.BENTO_CLOUD_API_KEY }}
        endpoint: ${{ secrets.BENTO_CLOUD_API_ENDPOINT }}
        EOF
        
    - name: Build and Push Bento
      run: |
        bentoml build
        bentoml push
      
    - name: Get latest Bento tag
      id: get_tag
      run: |
        BENTO_TAG=$(bentoml list -o json | jq -r '.[0].tag')
        echo "BENTO_TAG=${BENTO_TAG}" >> $GITHUB_ENV
        
    - name: Update Deployment
      env:
        BENTO_CLOUD_API_KEY: ${{ secrets.BENTO_CLOUD_API_KEY }}
        BENTO_CLOUD_API_ENDPOINT: ${{ secrets.BENTO_CLOUD_API_ENDPOINT }}
      run: |
        python - <<EOF
        import bentoml
        import os
        
        # Configure BentoML client
        bentoml.set_cloud_api_token(os.environ["BENTO_CLOUD_API_KEY"])
        bentoml.set_cloud_endpoint(os.environ["BENTO_CLOUD_API_ENDPOINT"])
        
        # Update deployment with new Bento
        bentoml.deployment.update(
            name="housing-model-v1",
            bento="${{ env.BENTO_TAG }}"
        )
        EOF 